# Active Profile: Choose 'h2' or 'mysql'
# To switch profiles, change the value below or use: mvn spring-boot:run -Dspring-boot.run.profiles=h2
spring.profiles.active=mysql
# Common Configuration
server.port=8080